### ISSUE TITLE
Can not import correctly

### ISSUE THREAD

**Issue by yy997** [Odoo-mobile/notes#10]
i import the Project into Android Studio,but it remind a error about:
Error:(80, 9) Element receiver#com.odoo.server.notifications.OdooServerNotificationReceiver at AndroidManifest.xml:80:9 duplicated with element declared at AndroidManifest.xml:74:9

**Comment by dpr-odoo** [comment]
@yy997 Removed duplicate receiver entry. https://github.com/Odoo-mobile/notes/commit/75b551496736ecedbf8e442db7a34ca183ba380e take updated pull.
